# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9e5c6a521adc3c634114e5817ada5c2a56437beff78809ea07ef1de40087e4027396d2760d8e795b2bddda361cf97ad18fcf7c8367b817f9941145e43d8541d6

test:
  secret_key_base: 12d162a1983c323afadf02d45b933fef4cde6d3f0f0f3ee5e4476d870f321a44391e815ffb8a9af43bcce10beca6a3e56c5d8f6dd141634716c0b681b35b4e52

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
